[features]
seeds = false
skip-lint = false

[programs.devnet]
vault = "5B8QtPsScaQsw392vnGnUaoiRQ8gy5LzzKdNeXe4qghR"

[programs.mainnet]
vault = "5B8QtPsScaQsw392vnGnUaoiRQ8gy5LzzKdNeXe4qghR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[toolchain]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types = "target/types"