# XORJ Quantitative Engine - Development Environment
version: '3.8'

services:
  # Main Application
  quantitative-engine:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://xorj:xorj_password@postgres:5432/xorj_quant
      - REDIS_URL=redis://redis:6379
      - SOLANA_RPC_URL=${SOLANA_RPC_URL:-https://api.devnet.solana.com}
      - HELIUS_API_KEY=${HELIUS_API_KEY}
      - LOG_LEVEL=INFO
      - ENVIRONMENT=development
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - xorj-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=xorj_quant
      - POSTGRES_USER=xorj
      - POSTGRES_PASSWORD=xorj_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - xorj-network
    restart: unless-stopped

  # Redis for Task Queue
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - xorj-network
    restart: unless-stopped

  # Celery Worker for Background Tasks
  celery-worker:
    build: .
    command: celery -A app.worker worker --loglevel=info --concurrency=2
    environment:
      - DATABASE_URL=postgresql://xorj:xorj_password@postgres:5432/xorj_quant
      - REDIS_URL=redis://redis:6379
      - SOLANA_RPC_URL=${SOLANA_RPC_URL:-https://api.devnet.solana.com}
      - HELIUS_API_KEY=${HELIUS_API_KEY}
      - LOG_LEVEL=INFO
      - ENVIRONMENT=development
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    networks:
      - xorj-network
    restart: unless-stopped

  # Celery Beat for Scheduled Tasks
  celery-beat:
    build: .
    command: celery -A app.worker beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - DATABASE_URL=postgresql://xorj:xorj_password@postgres:5432/xorj_quant
      - REDIS_URL=redis://redis:6379
      - SOLANA_RPC_URL=${SOLANA_RPC_URL:-https://api.devnet.solana.com}
      - HELIUS_API_KEY=${HELIUS_API_KEY}
      - LOG_LEVEL=INFO
      - ENVIRONMENT=development
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    networks:
      - xorj-network
    restart: unless-stopped

  # Flower for Celery Monitoring (Development)
  flower:
    build: .
    command: celery -A app.worker flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - xorj-network
    profiles: ["dev"]

networks:
  xorj-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: